USE MEUFUNCIONARIO;




-- 1)
SELECT * FROM DBO.BANCOS
ORDER BY NM_BANCO, NU_AGENCIA ASC

----------

-- 2) JOIN JUNSTA 2 TABELAS
SELECT NM_BANCO FROM DBO.BANCOS B LEFT JOIN DBO.FUNCIONARIOS F ON B.CD_BANCO = F.CD_BANCO 
WHERE F.CD_FUNCIONARIO IS NULL 

-- 3)
SELECT NM_BANCO FROM DBO.BANCOS
WHERE NU_BANCO LIKE '1%' OR NU_AGENCIA IS NULL 

-- 4)
SELECT NM_FUNCIONARIO FROM DBO.FUNCIONARIOS
WHERE VL_SALARIO <= 200 AND YEAR(DT_NASCIMENTO) > 1974

SELECT * FROM DBO.FUNCIONARIOS
WHERE VL_SALARIO <= 200 AND YEAR(DT_NASCIMENTO) > 1974

-- 5)
SELECT NM_FUNCIONARIO  FROM DBO.FUNCIONARIOS
WHERE  MONTH(DT_ADMISSAO) = 2;


-----------------------------
-- 6)
SELECT * FROM DBO.FUNCIONARIOS F JOIN DBO.DEPARTAMENTOS D ON F.CD_DEPARTAMENTO = D.CD_DEPARTAMENTO
WHERE F.CD_DEPARTAMENTO IS NULL 
AND F.CD_BANCO IS NOT NULL
----------------------------


--------------------------------------
--7)
SELECT F.NM_FUNCIONARIO, D.NM_DEPARTAMENTO, B.NM_BANCO 
FROM DBO.FUNCIONARIOS F  JOIN DBO.DEPARTAMENTOS D ON F.CD_DEPARTAMENTO = D.CD_DEPARTAMENTO
LEFT JOIN DBO.BANCOS B ON F.CD_BANCO = B.CD_BANCO
----------------------------------------


------------------------------
--8)

SELECT F.NM_FUNCIONARIO AS [Nome do Funcionário],
D.NM_DEPARTAMENTO AS [Departamento],
ISNULL(B.NM_BANCO, 'CONTA INEXISTENTE') AS [Banco]
FROM DBO.FUNCIONARIOS F JOIN DBO.DEPARTAMENTOS D ON F.CD_DEPARTAMENTO = D.CD_DEPARTAMENTO
LEFT JOIN DBO.BANCOS B ON F.CD_BANCO = B.CD_BANCO
ORDER BY B.CD_BANCO DESC


--9) SELECIONAR OS FUNCIONARIOS QUE TENHAM CONTA NO BANCO DO BRASIL E TRABALHEM NO DEPARTAMENTO DE DESENVOLVIMENTO
-- OU QUE TRABALHAM NO DEPARTAMENTO DE RECURSOS HUMANOS E NÃO TENHAM CONTA EM NENHUM BANCO,
-- MOSTRANDO O NOME DO FUNCIONARIO, O DEPARTAMENTO E O BANCO




SELECT F.NM_FUNCIONARIO, B.NM_BANCO, D.NM_DEPARTAMENTO 
FROM FUNCIONARIOS F LEFT JOIN BANCOS B ON F.CD_BANCO = B.CD_BANCO
LEFT JOIN DEPARTAMENTOS D ON F.CD_DEPARTAMENTO = D.CD_DEPARTAMENTO
WHERE F.CD_BANCO = 1 AND F.CD_DEPARTAMENTO =1
OR F.CD_BANCO IS NULL AND F.CD_DEPARTAMENTO = 4;


/*10) SELECIONAR OS FUNCIONARIOS, MOSTRANDO O NOME DO FUNCIONARIO, A DATA DE ADMISSÃO, O SALARIO ATUAL,
 UMA MENSAGEM NAS SEGUINTES CONDIÇÕES:
 1- SE FORAM ADMITIDOS ANTES DE 2000, MENSAGEM: "SENIOR"

 2- SE FOI ADMITIDO ENTRE OS ANOS 2000 E 2014, MENSAGEM: "PLENO"

 3-SE FOI ADMITIDO DEPOIS DE 2014, MENSAGEM: "NOVATO"

 E UMA COLUNA CHAMADA "SALARIO PREVISTO" COM O AUMENTO DE 12,4% PARA OS FUNCIONARIOS NOVATOS COM CONTA NO BRADESCO DA AGENCIA 500-4
 e aumento de 15% para os funcionários plenos que tiverem conta na caixa econômica Federal.

 */

 DECLARE @MEN VARCHAR(50);

 SELECT MENSAGEM =  IIF(YEAR(F.DT_ADMISSAO) < 2000, 'SENIOR',
   IIF( YEAR(F.DT_ADMISSAO) < 2014, 'PLENO',
   IIF(YEAR(F.DT_ADMISSAO) > 2014 , 'NOVATO', '')))
  
   
   FROM FUNCIONARIOS F 

 SELECT F.NM_FUNCIONARIO, F.DT_ADMISSAO, F.VL_SALARIO,  IIF(YEAR(F.DT_ADMISSAO) < 2000, 'SENIOR',
   IIF( YEAR(F.DT_ADMISSAO) < 2014, 'PLENO',
   IIF(YEAR(F.DT_ADMISSAO) > 2014 , 'NOVATO', ''))) AS MENSAGEM,
   CASE	
		WHEN YEAR(F.DT_ADMISSAO) > 2014 AND NM_BANCO = 'Bradesco' THEN VL_SALARIO *1.1235
		WHEN YEAR(F.DT_ADMISSAO) BETWEEN 200 AND 2014 AND NM_BANCO = 'Caixa Econômica Federal' THEN VL_SALARIO *1.5
		WHEN YEAR(F.DT_ADMISSAO) = YEAR(F.DT_ADMISSAO) THEN VL_SALARIO
	END 
AS [SALARIO PREVISTO ]
   
FROM FUNCIONARIOS F LEFT JOIN BANCOS B ON B.CD_BANCO = F.CD_BANCO





-- 11)Fazer um relatório que para cada departamento mostre o nome do departamento e a quantidade
-- de pessoas que foram admitidos antes do ano 2000, entre o ano 2000 e 2014 e depois de 2014.



SELECT D.NM_DEPARTAMENTO, 
	QTN_SENIOR = SUM(IIF(YEAR(F.DT_ADMISSAO) < 2000,1,0)),
	QTN_PLENO = SUM(IIF(YEAR(F.DT_ADMISSAO) BETWEEN 2000 AND 2014,1,0)),
	QTN_NOVATO = SUM(IIF(YEAR(F.DT_ADMISSAO) > 2014,1,0))
 FROM FUNCIONARIOS F  
 JOIN DEPARTAMENTOS D ON F.CD_DEPARTAMENTO = D.CD_DEPARTAMENTO
 GROUP BY D.NM_DEPARTAMENTO
 



 --- TABELA TEMPORARIA, SO EXISTE AQUI NESSA SEÇÃO VULGO(55)

 CREATE TABLE #X (ID INT IDENTITY(1,1), NOME VARCHAR(100), DT_NASCIMENTO DATETIME)

 SELECT * FROM #X

  --- TABELA TEMPORARIA GLOBAL, POSSIVEL VISUALIZAR EM OUTRAS SEÇÕES

 CREATE TABLE ##X (ID INT IDENTITY(1,1), NOME VARCHAR(100), DT_NASCIMENTO DATETIME)

 INSERT INTO ##X(NOME, DT_NASCIMENTO) VALUES ('DIOGO', 01/02/1000)

 SELECT * FROM ##X
 

 SELECT D.NM_DEPARTAMENTO, COUNT(*) [QNTD_DE_FUN_DEPARTAMENTO] FROM FUNCIONARIOS F JOIN DEPARTAMENTOS D ON F.CD_DEPARTAMENTO = D.CD_DEPARTAMENTO
 GROUP BY D.NM_DEPARTAMENTO 




-------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE #T ( NOME_DART VARCHAR(50), QTD INT)

INSERT INTO #T(NOME_DART, QTD) SELECT D.NM_DEPARTAMENTO, COUNT(*) 
FROM FUNCIONARIOS F JOIN DEPARTAMENTOS D 
ON F.CD_DEPARTAMENTO = D.CD_DEPARTAMENTO
GROUP BY D.NM_DEPARTAMENTO 

SELECT * FROM #T 
-------------------------------------------------------------------------------------------------------------------------------------------------------

SELECT F.CD_DEPARTAMENTO, COUNT(F.NM_FUNCIONARIO) NUMERO INTO #TMP FROM FUNCIONARIOS F 
GROUP BY F.CD_DEPARTAMENTO

SELECT * FROM #TMP

SELECT D.NM_DEPARTAMENTO, COUNT(*) NUMERO INTO #TMPPP FROM FUNCIONARIOS F JOIN DEPARTAMENTOS D
ON F.CD_DEPARTAMENTO = D.CD_DEPARTAMENTO
GROUP BY D.NM_DEPARTAMENTO

SELECT * FROM #TMPPP


---------------------------------------------------------------------------------------------------------------------------------------





CREATE TABLE #P ( NOME_DART VARCHAR(50), QTD INT)

SELECT P.NOME_DART, (SELECT COUNT(*) FROM FUNCIONARIOS F JOIN DEPARTAMENTOS D ON F.CD_DEPARTAMENTO = D.CD_DEPARTAMENTO
)AS QTD FROM #P P 

SELECT * FROM #P