USE MEUFUNCIONARIO;

SELECT * FROM DBO.DEPARTAMENTOS
-- 1)
SELECT * FROM DBO.BANCOS
ORDER BY NM_BANCO, NU_AGENCIA ASC

----------

-- 2) JOIN JUNSTA 2 TABELAS
SELECT NM_BANCO FROM DBO.BANCOS B LEFT JOIN DBO.FUNCIONARIOS F ON B.CD_BANCO = F.CD_BANCO 
WHERE F.CD_FUNCIONARIO IS NULL 

-- 3)
SELECT NM_BANCO FROM DBO.BANCOS
WHERE NU_BANCO LIKE '1%' OR NU_AGENCIA IS NULL 

-- 4)
SELECT NM_FUNCIONARIO FROM DBO.FUNCIONARIOS
WHERE VL_SALARIO <= 200 AND YEAR(DT_NASCIMENTO) > 1974

SELECT * FROM DBO.FUNCIONARIOS
WHERE VL_SALARIO <= 200 AND YEAR(DT_NASCIMENTO) > 1974

-- 5)
SELECT NM_FUNCIONARIO  FROM DBO.FUNCIONARIOS
WHERE  MONTH(DT_ADMISSAO) = 2;

SELECT *, MES_ANO = CONCAT( MONTH(DT_ADMISSAO) , '/' , YEAR(DT_ADMISSAO))  FROM DBO.FUNCIONARIOS
WHERE  MONTH(DT_ADMISSAO) = 2;

SELECT *, MES_ANO = FORMAT(CAST(CONCAT('1/',MONTH(DT_ADMISSAO) , '/' , YEAR(DT_ADMISSAO)) AS DATE), 'MM/yyyy')  FROM DBO.FUNCIONARIOS
WHERE  MONTH(DT_ADMISSAO) = 2;


--SELECT * FROM DBO.FUNCIONARIOS F JOIN DBO.DEPARTAMENTOS D ON F.CD_DEPARTAMENTO = D.CD_DEPARTAMENTO WHERE
--F.CD_BANCO = 2;


SELECT GETDATE();

SELECT *,IDADE =  DATEDIFF(YEAR, DT_NASCIMENTO, GETDATE()), TEMPODESERVICO =  DATEDIFF(YEAR, DT_ADMISSAO, GETDATE())
FROM DBO.FUNCIONARIOS


SELECT *,MAISQUE15 = DATEDIFF(YEAR, DT_ADMISSAO, GETDATE())
FROM DBO.FUNCIONARIOS WHERE YEAR(DT_ADMISSAO) < 2007

-------------------------------------------------

SELECT *FROM ( SELECT *, DATEDIFF(YEAR, DT_ADMISSAO, GETDATE()) AS SERVICOTEMP
FROM DBO.FUNCIONARIOS) F WHERE SERVICOTEMP > 15;

--------------------------------------------------

SELECT *,MAISQUE15 = DATEDIFF(YEAR, DT_ADMISSAO, GETDATE())
FROM DBO.FUNCIONARIOS

SELECT DATEDIFF(month,       '2005-12-31 23:59:59.9999999', '2006-01-01 00:00:00.0000000');


-----------------------------
-- 6)
SELECT * FROM DBO.FUNCIONARIOS F LEFT JOIN DBO.DEPARTAMENTOS D ON F.CD_DEPARTAMENTO = D.CD_DEPARTAMENTO
WHERE F.CD_DEPARTAMENTO IS NULL 
AND F.CD_BANCO IS NOT NULL
----------------------------


--------------------------------------
--7)
SELECT F.NM_FUNCIONARIO, D.NM_DEPARTAMENTO, B.NM_BANCO 
FROM DBO.FUNCIONARIOS F LEFT JOIN DBO.DEPARTAMENTOS D ON F.CD_DEPARTAMENTO = D.CD_DEPARTAMENTO
LEFT JOIN DBO.BANCOS B ON F.CD_BANCO = B.CD_BANCO
----------------------------------------