'1 -' SELECT* FROM BANCOS ORDER BY NM_BANCO, NU_AGENCIA

'2 -' SELECT NM_BANCO FROM BANCOS B JOIN FUNCIONARIOS F ON B.CD_BANCO = F.CD_BANCO WHERE CD_BANCO IS NULL

'3 -' SELECT NM_BANCO FROM BANCOS WHERE NU_BANCO IS NULL OR NU_BANCO LIKE '1%'

'4 -' SELECT NM_FUNCIONARIO FROM FUNCIONARIOS WHERE SALARIO <= 200.00 AND YEAR(DT_NASCIMENTO) > 1974

'5 -' SELECT NM_FUNCIONARIO FROM FUNCIONARIOS WHERE MONTH(DT_ADMISSAO) = 2