USE MEUFUNCIONARIO;

INSERT INTO DBO.DEPARTAMENTO VALUES( 'Desenvolvimento'),
( 'Financeiro'),
( 'Editoração');

SELECT * FROM DBO.DEPARTAMENTO;



DECLARE @NOME VARCHAR(100);

-- DELETE  FROM DBO.DEPARTAMENTO WHERE CD_DEPARTAMENTO > 1;