


------------------------- PIVOT-------------------------------


SELECT VL_SALARIO, COUNT(*) TOTAL
FROM FUNCIONARIOS GROUP BY VL_SALARIO

SELECT * FROM
( SELECT VL_SALARIO
FROM FUNCIONARIOS) t
PIVOT(
COUNT(VL_SALARIO)
FOR VL_SALARIO IN (
[180.00],
[189.00],
[200.00],
[500.00],
[800.00],
[1500.00])
) AS pivot_table;



DECLARE @SQL VARCHAR(MAX) = '
SELECT ''AverageCost'' AS Cost_Sorted_By_Production_Days,   
  [0], [1], [2], [3], [4]  
FROM  
(
  SELECT DaysToManufacture, StandardCost   
  FROM Production.Product
) AS SourceTable  
PIVOT  
(  
  AVG(StandardCost)  
  FOR DaysToManufacture IN ([0], [1], [2], [3], [4])  
) AS PivotTable; '

EXEC(@SQL)


----- MEDIA DE SALARIO POR DEPARTAMENTO

----------------------------- CORRETO --------------------------------------------------
SELECT * FROM ( SELECT  D.NM_DEPARTAMENTO,T.VL_SALARIO 
				FROM FUNCIONARIOS T JOIN DEPARTAMENTOS D 
				ON T.CD_DEPARTAMENTO = D.CD_DEPARTAMENTO) F
PIVOT (AVG(F.VL_SALARIO)
FOR F.NM_DEPARTAMENTO IN ([DESENVOLVIMENTO],[EDITORAÇÃO],[FINANCEIRO],[RECURSOS HUMANOS] )
) AS PIVOT_TABLE

-----------------------------------------------------------------------------------------






-------------------- UPIVOT------------------------------------------------------------------






-----------------------------------------------------------------------------------------------

-------------------- JSON------------------------------------------------------------------

SELECT * FROM FUNCIONARIOS F
FOR JSON PATH

SELECT * FROM FUNCIONARIOS F
FOR JSON AUTO

DECLARE @JS VARCHAR(MAX) = '
[{"CD_FUNCIONARIO":1,"NM_FUNCIONARIO":"Antônio Nascimento","CD_DEPARTAMENTO":3,"DT_ADMISSAO":"1992-01-10T00:00:00","DT_NASCIMENTO":"1974-01-10T00:00:00","VL_SALARIO":200.0000},{"CD_FUNCIONARIO":2,"NM_FUNCIONARIO":"João Anastácio","CD_DEPARTAMENTO":1,"DT_ADMISSAO":"2005-01-01T00:00:00","DT_NASCIMENTO":"1987-01-01T00:00:00","CD_BANCO":1,"VL_SALARIO":500.0000},{"CD_FUNCIONARIO":3,"NM_FUNCIONARIO":"João Malha","CD_DEPARTAMENTO":4,"DT_ADMISSAO":"2009-04-10T00:00:00","DT_NASCIMENTO":"1991-04-10T00:00:00","CD_BANCO":4,"VL_SALARIO":189.0000},{"CD_FUNCIONARIO":4,"NM_FUNCIONARIO":"Manoel da R. Pizzolo","CD_DEPARTAMENTO":3,"DT_ADMISSAO":"2015-05-02T00:00:00","DT_NASCIMENTO":"1997-05-02T00:00:00","CD_BANCO":3,"VL_SALARIO":1500.0000},{"CD_FUNCIONARIO":5,"NM_FUNCIONARIO":"Maria de Jesus","CD_DEPARTAMENTO":4,"DT_ADMISSAO":"1998-02-11T00:00:00","DT_NASCIMENTO":"1980-02-11T00:00:00","VL_SALARIO":180.0000},{"CD_FUNCIONARIO":6,"NM_FUNCIONARIO":"Pedro Brasona","CD_DEPARTAMENTO":2,"DT_ADMISSAO":"2019-02-05T00:00:00","DT_NASCIMENTO":"2001-02-05T00:00:00","CD_BANCO":2,"VL_SALARIO":800.0000},{"CD_FUNCIONARIO":7,"NM_FUNCIONARIO":"Raimundo Pizzolo","CD_DEPARTAMENTO":4,"DT_ADMISSAO":"1998-02-11T00:00:00","DT_NASCIMENTO":"1980-02-11T00:00:00","VL_SALARIO":180.0000}]'

SELECT * FROM OPENJSON(@JS)
WITH(CD_FUNCIONARIO INT,
 NM_FUNCIONARIO VARCHAR(150),
 CD_DEPARTAMENTO INT,
 DT_ADIMISSAO DATETIME,
 DT_NASCIMENTO DATETIME,
 VL_SALARIO MONEY
  )AS MONTHS

-----------------------------------------------------------------------------------------------
SELECT * FROM DEPARTAMENTOS
FOR JSON PATH

DECLARE @J VARCHAR(MAX) = '[{"CD_DEPARTAMENTO":1,"NM_DEPARTAMENTO":"Desenvolvimento"},{"CD_DEPARTAMENTO":2,"NM_DEPARTAMENTO":"Editoração"},{"CD_DEPARTAMENTO":3,"NM_DEPARTAMENTO":"Financeiro"},{"CD_DEPARTAMENTO":4,"NM_DEPARTAMENTO":"Recursos Humanos"}]'
SELECT * FROM OPENJSON(@J)
WITH(CD_DEPARTAMENTO INT,
NM_DEPARTAMENTO VARCHAR(150))

----------------------------------------------------

SELECT * FROM BANCOS
FOR JSON PATH

DECLARE @B VARCHAR(MAX) = '[{"CD_BANCO":1,"NM_BANCO":"Banco do Brasil","NU_AGENCIA":"0407-3","NU_BANCO":"6620-6"},{"CD_BANCO":2,"NM_BANCO":"Bradesco","NU_AGENCIA":"500-4","NU_BANCO":"1246-88"},{"CD_BANCO":3,"NM_BANCO":"Bradesco","NU_AGENCIA":"345-1","NU_BANCO":"1232-2"},{"CD_BANCO":4,"NM_BANCO":"Caixa Econômica Federal","NU_AGENCIA":"0258-0","NU_BANCO":"104"},{"CD_BANCO":5,"NM_BANCO":"Itaú","NU_AGENCIA":"2323-24","NU_BANCO":"34534"}]'
SELECT * FROM OPENJSON(@B)
WITH(CD_BANCO INT,
NM_BANCO VARCHAR(50),
NU_AGENCIA VARCHAR(15),
NU_BANCO VARCHAR(15)
)


---------------------XML----------------------------
SELECT * FROM FUNCIONARIOS
FOR XML AUTO

DROP TABLE IF EXISTS #X
SELECT F.CD_DEPARTAMENTO, F.NM_FUNCIONARIO 
INTO #X
FROM FUNCIONARIOS F 
ORDER BY CD_DEPARTAMENTO

SELECT X1.CD_DEPARTAMENTO
, FUNCS = STUFF( (	SELECT CONCAT(',', X2.NM_FUNCIONARIO) 
					FROM #X X2 WHERE X2.CD_DEPARTAMENTO = X1.CD_DEPARTAMENTO 
					ORDER BY X2.NM_FUNCIONARIO 
					FOR XML PATH('')) , 1, 1, '')
FROM #X X1
GROUP BY X1.CD_DEPARTAMENTO





SELECT * FROM ( SELECT CD_DEPARTAMENTO, VL_SALARIO FROM FUNCIONARIOS) F
PIVOT ( AVG(VL_SALARIO)
FOR CD_DEPARTAMENTO IN ([1],[2],[3],[4])
) AS PIVOT_TABLE


SELECT * FROM DEPARTAMENTOS


SELECT *
FROM (SELECT CD_DEPARTAMENTO,VL_SALARIO
FROM FUNCIONARIOS) T
PIVOT ( AVG(VL_SALARIO)
FOR CD_DEPARTAMENTO IN ([1],[2],[3],[4])
) AS PIVOT_table

SELECT * FROM ( SELECT VL_SALARIO FROM FUNCIONARIOS) t
PIVOT(
COUNT(VL_SALARIO)
FOR VL_SALARIO IN (
[180.00],
[189.00],
[200.00],
[500.00],
[800.00],
[1500.00])
) AS pivot_table;

DECLARE
@columns NVARCHAR(MAX) = '',
@sql NVARCHAR(MAX) = '';
--------------------------------------
SELECT
@columns+=QUOTENAME(NM_DEPARTAMENTO) + ','
FROM
DEPARTAMENTOS
GROUP BY
NM_DEPARTAMENTO;
--------------------------------------
SET @columns = LEFT(@columns, LEN(@columns) - 1);
--------------------------------------
SELECT @columns
--------------------------------------
SET @sql ='SELECT * FROM
( SELECT D.NM_DEPARTAMENTO, F.VL_SALARIO
FROM FUNCIONARIOS F JOIN DEPARTAMENTOS D
ON F.CD_DEPARTAMENTO = D.CD_DEPARTAMENTO) t
PIVOT(
AVG(VL_SALARIO)
FOR NM_DEPARTAMENTO IN ('+ @columns +'))AS pivot_table';
--------------------------------------
EXECUTE (@sql);