--CREATE DATABASE F2

DROP TABLE IF EXISTS [dbo].[FUNCIONARIOS]
DROP TABLE IF EXISTS [dbo].[DEPARTAMENTOS]
DROP TABLE IF EXISTS [dbo].[BANCOS]

CREATE TABLE [dbo].[BANCOS]
(
	[CD_BANCO] [int] IDENTITY(1,1) NOT NULL,
	[NM_BANCO] [varchar](150) NULL,
	[NU_AGENCIA] [varchar](15) NULL,
	[NU_BANCO] [varchar](15) NULL,
	CONSTRAINT [PK_BANCOS] PRIMARY KEY CLUSTERED ([CD_BANCO] ASC)
	)

CREATE TABLE [dbo].[DEPARTAMENTOS]
(
	[CD_DEPARTAMENTO] [int] IDENTITY(1,1) NOT NULL,
	[NM_DEPARTAMENTO] [varchar](150) NULL,
	CONSTRAINT [PK_DEPARTAMENTOS] PRIMARY KEY CLUSTERED ([CD_DEPARTAMENTO] ASC)
)

CREATE TABLE [dbo].[FUNCIONARIOS]
(
	[CD_FUNCIONARIO] [int] IDENTITY(1,1) NOT NULL,
	[NM_FUNCIONARIO] [varchar](150) NULL,
	[CD_DEPARTAMENTO] [int] NULL,
	[DT_ADMISSAO] [datetime] NULL,
	[DT_NASCIMENTO] [datetime] NULL,
	[CD_BANCO] [int] NULL,
	[VL_SALARIO] [money] NULL,
	CONSTRAINT [PK_FUNCIONARIOS] PRIMARY KEY CLUSTERED ([CD_FUNCIONARIO] ASC),
	CONSTRAINT [FK_FUNCIONARIOS_X_BANCOS] FOREIGN KEY([CD_BANCO]) REFERENCES [dbo].[BANCOS] ([CD_BANCO]),
	CONSTRAINT [FK_FUNCIONARIOS_X_DEPARTAMENTOS] FOREIGN KEY([CD_DEPARTAMENTO]) REFERENCES [dbo].[DEPARTAMENTOS] ([CD_DEPARTAMENTO])
)

INSERT INTO DEPARTAMENTOS (NM_DEPARTAMENTO) VALUES('Desenvolvimento')
INSERT INTO DEPARTAMENTOS (NM_DEPARTAMENTO) VALUES('Editoração')
INSERT INTO DEPARTAMENTOS (NM_DEPARTAMENTO) VALUES('Financeiro')
INSERT INTO DEPARTAMENTOS (NM_DEPARTAMENTO) VALUES('Recursos Humanos')

INSERT INTO BANCOS (NM_BANCO,NU_AGENCIA,NU_BANCO) VALUES('Banco do Brasil', '0407-3', '6620-6')
INSERT INTO BANCOS (NM_BANCO,NU_AGENCIA,NU_BANCO) VALUES('Bradesco', '500-4', '1246-88')
INSERT INTO BANCOS (NM_BANCO,NU_AGENCIA,NU_BANCO) VALUES('Bradesco', '345-1', '1232-2')
INSERT INTO BANCOS (NM_BANCO,NU_AGENCIA,NU_BANCO) VALUES('Caixa Econômica Federal', '0258-0', '104')
INSERT INTO BANCOS (NM_BANCO,NU_AGENCIA,NU_BANCO) VALUES('Itaú', '2323-24', '34534')

INSERT INTO FUNCIONARIOS (NM_FUNCIONARIO,CD_DEPARTAMENTO,DT_ADMISSAO,DT_NASCIMENTO,CD_BANCO,VL_SALARIO) VALUES('Antônio Nascimento', 3, '19920110 00:00:00', '19740110 00:00:00', NULL, 200.00)
INSERT INTO FUNCIONARIOS (NM_FUNCIONARIO,CD_DEPARTAMENTO,DT_ADMISSAO,DT_NASCIMENTO,CD_BANCO,VL_SALARIO) VALUES('João Anastácio', 1, '20050101 00:00:00', '19870101 00:00:00', 1, 500.00)
INSERT INTO FUNCIONARIOS (NM_FUNCIONARIO,CD_DEPARTAMENTO,DT_ADMISSAO,DT_NASCIMENTO,CD_BANCO,VL_SALARIO) VALUES('João Malha', 4, '20090410 00:00:00', '19910410 00:00:00', 4, 189.00)
INSERT INTO FUNCIONARIOS (NM_FUNCIONARIO,CD_DEPARTAMENTO,DT_ADMISSAO,DT_NASCIMENTO,CD_BANCO,VL_SALARIO) VALUES('Manoel da R. Pizzolo', 3, '20150502 00:00:00', '19970502 00:00:00', 3, 1500.00)
INSERT INTO FUNCIONARIOS (NM_FUNCIONARIO,CD_DEPARTAMENTO,DT_ADMISSAO,DT_NASCIMENTO,CD_BANCO,VL_SALARIO) VALUES('Maria de Jesus', 4, '19980211 00:00:00', '19800211 00:00:00', NULL, 180.00)
INSERT INTO FUNCIONARIOS (NM_FUNCIONARIO,CD_DEPARTAMENTO,DT_ADMISSAO,DT_NASCIMENTO,CD_BANCO,VL_SALARIO) VALUES('Pedro Brasona', 2, '20190205 00:00:00', '20010205 00:00:00', 2, 800.00)
INSERT INTO FUNCIONARIOS (NM_FUNCIONARIO,CD_DEPARTAMENTO,DT_ADMISSAO,DT_NASCIMENTO,CD_BANCO,VL_SALARIO) VALUES('Raimundo Pizzolo', 4, '19980211 00:00:00', '19800211 00:00:00', NULL, 180.00)


SELECT * FROM BANCOS
SELECT * FROM DEPARTAMENTOS
SELECT * FROM FUNCIONARIOS
