CREATE DATABASE MEUFUNCIONARIO;

USE MEUFUNCIONARIO;

CREATE TABLE BANCOS(CD_BANCO INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
NM_BANCO VARCHAR(150) NOT NULL,
AGENCIA INT,
NUMERO_BANCO INT
);

CREATE TABLE FUNCIONARIOS(CD_FUNCIONARIO INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
CD_DEPARTAMENTO INT NOT NULL,
CD_BANCO INT NOT NULL,
NM_FUNCIONARIO VARCHAR(150) NOT NULL,
DT_ADMISSAO DATETIME,
DT_NASCIMENTO DATETIME,
);

CREATE TABLE DEPARTAMENTO(CD_DEPARTAMENTO INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
NM_DEPARTAMENTO VARCHAR(150) NOT NULL,

);


ALTER TABLE FUNCIONARIOS
ADD CONSTRAINT FK_FUNCIONARIO_X_BANCOS
FOREIGN KEY (CD_BANCO)
REFERENCES BANCOS(CD_BANCO);


ALTER TABLE FUNCIONARIOS
ADD CONSTRAINT FK_FUNCIONARIO_X_DEPARTAMENTO
FOREIGN KEY (CD_DEPARTAMENTO)
REFERENCES DEPARTAMENTO(CD_DEPARTAMENTO);
