


SELECT D.NM_DEPARTAMENTO, 
	QTN_SENIOR = SUM(IIF(YEAR(F.DT_ADMISSAO) < 2000,1,0)),
	QTN_PLENO = SUM(IIF(YEAR(F.DT_ADMISSAO) BETWEEN 2000 AND 2014,1,0)),
	QTN_NOVATO = SUM(IIF(YEAR(F.DT_ADMISSAO) > 2014,1,0))
 FROM FUNCIONARIOS F  
 JOIN DEPARTAMENTOS D ON F.CD_DEPARTAMENTO = D.CD_DEPARTAMENTO
 GROUP BY D.NM_DEPARTAMENTO
 

 
SELECT NM_DEPARTAMENTO, 
	QTN_SENIOR = (SELECT ISNULL(SUM(1), 0) FROM FUNCIONARIOS WHERE YEAR(DT_ADMISSAO) < 2000 AND CD_DEPARTAMENTO = D.CD_DEPARTAMENTO),
	QTN_PLENO = (SELECT ISNULL(SUM(1), 0) FROM FUNCIONARIOS WHERE YEAR(DT_ADMISSAO) BETWEEN 2000 AND 2014 AND CD_DEPARTAMENTO = D.CD_DEPARTAMENTO),
	QTN_NOVATO = (SELECT ISNULL(SUM(1), 0) FROM FUNCIONARIOS WHERE YEAR(DT_ADMISSAO) > 2014 AND CD_DEPARTAMENTO = D.CD_DEPARTAMENTO)
 FROM DEPARTAMENTOS D ORDER BY NM_DEPARTAMENTO

 SELECT NM_DEPARTAMENTO, 
	QTN_SENIOR = (SELECT COUNT(*) FROM FUNCIONARIOS WHERE YEAR(DT_ADMISSAO) < 2000 AND CD_DEPARTAMENTO = D.CD_DEPARTAMENTO),
	QTN_PLENO = (SELECT COUNT(*) FROM FUNCIONARIOS WHERE YEAR(DT_ADMISSAO) BETWEEN 2000 AND 2014 AND CD_DEPARTAMENTO = D.CD_DEPARTAMENTO),
	QTN_NOVATO = (SELECT COUNT(*) FROM FUNCIONARIOS WHERE YEAR(DT_ADMISSAO) > 2014 AND CD_DEPARTAMENTO = D.CD_DEPARTAMENTO)
 FROM DEPARTAMENTOS D ORDER BY NM_DEPARTAMENTO

 






