USE MEUFUNCIONARIO


---------- SUB CONSULTA NO WHERE COM O USO DO IN --------------------------

SELECT F.NM_FUNCIONARIO, F.CD_BANCO FROM FUNCIONARIOS F
WHERE F.CD_BANCO IN (SELECT CD_BANCO FROM BANCOS B WHERE B.NU_AGENCIA = '345-1')


--------------------------- SUB CONSULTA NO WHERE COM O USO DO EXISTS
SELECT F.NM_FUNCIONARIO FROM FUNCIONARIOS F
WHERE EXISTS (SELECT CD_BANCO FROM BANCOS B WHERE B.NU_AGENCIA = '345-1' AND B.CD_BANCO = F.CD_BANCO)



SELECT * FROM BANCOS B